version: "2"

services:
  pipeline-checkov:
    build:
      context: ./
    command: npx --yes --package '@quantum-sec/ci-analysis-collector' --call 'ci-analysis-collector checkov --path /workspace/'
    volumes:
      - ".submodules/terragoat:/workspace/"
