FROM quantumsec/docker-pipeline-checkov:latest

# Bash is required by Azure DevOps
# See: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#requirements
RUN apk add --update bash
